### ISSUE TITLE
Rotate the Meals sheet to read more like a calendar

### ISSUE THREAD

**Issue by boatbomber** [Ho1yShif/dinner#7]
This is the current layout:
![image](https://github.com/Ho1yShif/dinner/assets/40185666/fbcc8d24-44fe-459f-bfff-63d6a3dc0056)

A layout like this would be more easily readable at a glance, as it matches the way a standard calendar is read.
![image](https://github.com/Ho1yShif/dinner/assets/40185666/e3443350-9b5e-44b0-9610-3b024fa0f0c5)

In fact, the "Day" on the top left could be replaced with "Week Jan 07"

**Comment by Ho1yShif** [comment]
This issue was fixed with the [transpose menu](https://github.com/Ho1yShif/dinner/pull/9) PR. The menu now appears as formatted in the second image
